### PR TITLE
Migrate to null safety (NNBD)

### PR DESCRIPTION
**Pull request by jonas-zebari**
Since all dependencies are migrated to NNBD and Flutter 2.0 is released, I've migrated qr_flutter to null safety. I'm not sure everything is perfect yet, but all tests are still passing.

### CODE REVIEW

**Review by vishnuagbly — CHANGES_REQUESTED** [review]
update CHANGELOG.md too.

**Review by vishnuagbly — APPROVED** [review]

**Comment by lukepighetti** [comment]
@jonas-zebari I see the other PR, but neither have been triaged yet. Was there any reason why you closed this PR?

**Comment by jonas-zebari** [comment]
@lukepighetti The day after I opened this PR, #129 was opened and get a considerable amount of attention more than this PR, so I figured it was favored. Didn't see a point in having two null safety PRs.

**Comment by lukepighetti** [comment]
Do you have a preference between the two PRs?

**Comment by lukepighetti** [comment]
If you believe this PR is ready for code review please open it again.

**Comment by lukepighetti** [comment]
closed by super-PR https://github.com/theyakka/qr.flutter/pull/130, thanks @jonas-zebari

**Pull request closed without merging**
