### PR TITLE
Added custom styling for eye and eyeball

### PR DESCRIPTION
**Pull request by gibahjoe**
Added ability to style the eye and the eyeball

see examples
qr-code (4)
qr-code (3)
qr-code (2)
qr-code (1)

here is the list of supported eye shapes inspired by https://www.qrcode-monkey.com/

Screenshot 2021-01-01 at 01 42 09

This PR also includes the cutout part of a PR that was sent earlier #56  

Please update pub.dev so that everyone can benefit from this

### CODE REVIEW

**Comment by Sheharyar566** [comment]
Waiting for this PR to be merged

**Comment by lukepighetti** [comment]
Closing this because it conflicts with null-safety. Thanks for the efforts! 

We'd be happy to take another look if you bring this up to date with `master`. Just re-open the PR when you're ready.

**Comment by gibahjoe** [comment]
Updated to master

**Comment by gibahjoe** [comment]
See new PR here #133

**Pull request closed without merging**
