### PR TITLE
update version dart

### PR DESCRIPTION
**Pull request by renanzdm**
update dart version

### CODE REVIEW

**Comment by renanzdm** [comment]
Ok, i Will add examples as documentário.

**Comment by renanzdm** [comment]
Adjust on documentation finished

**Comment by MBjoern** [comment]
indentation is still a bit off.

@theyakka would you mind having a look? I'd love to see this version update merged.

**Comment by renanzdm** [comment]
fix indentation

**Comment by MBjoern** [comment]
Looks good to me, tested it and works like a charm.

@lukef lukef would you mind merging this PR?

**Comment by MBjoern** [comment]
@lukepighetti Is anyone still maintaining this library? - or is there already an alternative fork of this?

**Comment by MrCsabaToth** [comment]
Why min SDK 21?

**Pull request closed without merging**
