### PR TITLE
Circular QR Style and Logo cutout

### PR DESCRIPTION
**Pull request by Salzanoo**
Added option to change Qr code style and to cut out a portion for the logo.

Example:
Screen Shot 2019-08-22 at 5 22 59 PM

### CODE REVIEW

**Comment by ndjido** [comment]
@Salzanoo thanks for you PR! It's something I'm looking into right now. Are you still working on that?

**Comment by ndjido** [comment]
@lukef could you let me know what are your expectation on this feature? I will be more than happy to help?

**Comment by lukef** [comment]
Let me check where I left off and report back ASAP

**Comment by ankur2136** [comment]
Hi Luke,
Any updates on this PR. About your other comments that you are looking into more customizations, there are some good options here https://www.qrcode-monkey.com/

**Comment by atov** [comment]
Hi guys!

Any news about this PR?

**Comment by lukepighetti** [comment]
Closing this because it conflicts with null-safety. Thanks for the efforts, though!

We'd be happy to take another look if you bring this up to date with `master`. Just re-open the PR when you're ready.

**Pull request closed without merging**
